-- Jobs Scheduling & Dispatch Module

-- Enum for job status
CREATE TYPE public.job_status AS ENUM (
    'Unscheduled',
    'Scheduled',
    'In Progress',
    'Completed',
    'Cancelled'
);

-- Jobs table
CREATE TABLE public.jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id bigint REFERENCES public.deals(id) ON DELETE SET NULL,
    property_id bigint REFERENCES public.properties(id) ON DELETE CASCADE,
    assigned_to_id uuid REFERENCES public.sales(id) ON DELETE SET NULL,
    status public.job_status NOT NULL DEFAULT 'Unscheduled',
    scheduled_at timestamptz,
    completed_at timestamptz,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN public.jobs.deal_id IS 'Link to the original deal';
COMMENT ON COLUMN public.jobs.property_id IS 'Service location for the job';
COMMENT ON COLUMN public.jobs.assigned_to_id IS 'Assigned salesperson/crew';
COMMENT ON COLUMN public.jobs.status IS 'Current status of the job';
COMMENT ON COLUMN public.jobs.scheduled_at IS 'Planned start date/time';

-- Indexes
CREATE INDEX idx_jobs_status ON public.jobs(status);
CREATE INDEX idx_jobs_assigned_to_id ON public.jobs(assigned_to_id);
CREATE INDEX idx_jobs_property_id ON public.jobs(property_id);

-- RLS
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- Read access for all authenticated users
CREATE POLICY jobs_read_authenticated
    ON public.jobs FOR SELECT
    USING (auth.role() = 'authenticated');

-- Self-manage for assigned user
CREATE POLICY jobs_self_manage
    ON public.jobs FOR ALL
    USING (assigned_to_id = auth.uid());


